### ISSUE TITLE
How Secure am i if keyfile is stored outside of cloud??

### ISSUE THREAD

**Issue by dakkusingh** [vgough/encfs#122]
I read this security report and was somewhat concerned.. 
https://defuse.ca/audits/encfs.htm

However, if my key is never uploaded to the cloud, is it still a concern that someone could try to brute force? Is there any way possible for anyone to decrypt the container if key is never shared?

**Comment by rfjakob** [comment]
When the keyfile is stored somewhere else, brute-forcing is out of the question.
The key finding in the report is `2.2. Stream Cipher Used to Encrypt Last File Block`. This means that you leak some data about the **modifications** that take place in the last block (1kB) of your files. To get that data, the attacker must have a copy of the file before and after the modification.

Depending on the data you store, this can be no concern at all (for example, photos and videos that do not change) or a big problem (letters that you are editing).

**Comment by dakkusingh** [comment]
> 2.2. Stream Cipher Used to Encrypt Last File Block

**Comment by rfjakob** [comment]
No, this always applies. The attack works without knowing anything about the key.

I have edited my answer above to make that clear.

What operating system are you on?

**Comment by dakkusingh** [comment]
Thank you for clarifying this. I wasnt sure if not having the key made you immune to this issue. Is there any way to protect against this?

I am on OSX 10.11.1

**Comment by rfjakob** [comment]
Fixing this issue requires an incompatible format change and there is currently no way to mitigate it. The whole issue is documented in this ticket: https://github.com/vgough/encfs/issues/9

If you were on Linux I would recommend you to try out [gocryptfs](https://github.com/rfjakob/gocryptfs)  (developed by myself). Gocryptfs fixes this issue and a few more and has gone through quite some testing on Linux.  However, on Mac OS X, you'd probably would be the first one to test it.

**Comment by Harry5001** [comment]
The problem should become relevant when saving a file multiple times / when someone has the file in multiple versions. I have a question to this: Does the problem only occur, when there are multiple encoded files of the exactly identic source-file, or is it also relevant if there are multiple files of the same source file that has been modified in the second version before encoding? Another question: In case of one file could be decoded because of multiple versions of that file, are there all other files also compromised that had been encoded with the same key? Or are these still secure as long as no second encoded version is available?

**Comment by benrubson** [comment]
Question is finally answered here : #439 👍
