### ISSUE TITLE
Feature: get encrypted root

### ISSUE THREAD

**Issue by axet** [vgough/encfs#153]
Hello!

To do some tasks on encrypted folder scripts need to know where encrypted folder of current mounted folder is. There is no way get such information yet.

Would be nice if encfsctl can show where encrypted root folder located based on mounted file. Find encrypted file already possible using inode.

~/encrypted/EFefadeDEDed
<->
~/decrypted/file1

**Comment by rfjakob** [comment]
I think /proc/self/mounts shows this information, can you check?

**Comment by axet** [comment]
I'm using encfs on mac, here is no /proc

**Comment by bengoodwyn** [comment]
There are a few options here:

1) Use the "ps" command to review the parameters provided to encfs when it was launched.
<pre><code>[~/src/encfs/build]
bencodes-> ./encfs ~/.enc ~/enc
EncFS Password: 
[~/src/encfs/build]
bencodes-> ps aux |grep encfs
bengoodwyn      89406   0.0  0.0  2423376    248 s001  R+    4:19PM   0:00.00 grep encfs
bengoodwyn      89402   0.0  0.0  2513056    944   ??  Ss    4:19PM   0:00.00 ./encfs /Users/bengoodwyn/.enc /Users/bengoodwyn/enc
</code></pre>
Notice that the source and target path parameters are on the command line for the mount.

2) Manually provide an "fsname" to change what appears in the mount output.
<pre><code>[~/src/encfs/build]
bencodes-> mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
encfs@osxfuse0 on /Users/bengoodwyn/enc (osxfusefs, local, nodev, nosuid, synchronous, mounted by bengoodwyn)
[~/src/encfs/build]
bencodes-> umount ~/enc
[~/src/encfs/build]
bencodes-> ./encfs -ofsname=~/.enc ~/.enc ~/enc
EncFS Password: 
[~/src/encfs/build]
bencodes-> mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
~/.enc on /Users/bengoodwyn/enc (osxfusefs, local, nodev, nosuid, synchronous, mounted by bengoodwyn)</code></pre>
Note that by specifying the "fsname=" mount option I changed the value of the source of the mount so that you could reference where this mount came from.

3) You can modify encfs to include an fsname mount option automatically that is based upon the root directory so that this fsname is automatically set. But, this changes the behavior of several things in a manner that might not be ideal for existing applications that make assumptions about what that fsname might mean.

4b0e89cc1cb6282bf2871518ebf73e876c0d9187 is the commit I am referring to.

<pre><code>bencodes-> ./encfs ~/.enc ~/enc
EncFS Password: 
[~/src/encfs/build]
bencodes-> mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
encfs#/Users/bengoodwyn/.enc/ on /Users/bengoodwyn/enc (osxfusefs, local, nodev, nosuid, synchronous, mounted by bengoodwyn)
</code></pre>

Given that the use case sounds primarily for a scripting need you have I might would choose option 1 as you can get that done without any code changes necessary.

**Comment by benrubson** [comment]
Closing this, as `-o fsname` does the job.
Thx 👍
