### ISSUE TITLE
Compression feature request

### ISSUE THREAD

**Issue by dustin-decker** [vgough/encfs#176]
I use the `--reverse` flag to provide on-the-fly encrypted access to my files for backing up to a cloud storage provider. Awesome feature, by the way.

A `--compression` flag to provide on-the-fly compression prior to encryption would be a very useful feature for saving space and bandwidth. Similarly it would enable on-the-fly decompression following decryption if used in `--standard` mode. Gzip is often chosen for protocol compression for its good cost/compression ratio.

**Comment by rfjakob** [comment]
I understand that this would be nice, but this is very hard to get right, given that EncFS must support random access. I don't want to be rude and close the issue immediately, but I don't see this happening.

**Comment by imperative** [comment]
Random access could be realistically implemented with manageable performance penalties, for example if files would be split into chunks (not physically on disk, but logically inside the code), and each compressed individually. NTFS does live file compression somehow and they must support some kind of random access at least.

But still, such a change to encfs would require a lot of development, testing, could introduce bugs, backwards-incompatibility, instability etc. It would be a very big feature. There are far more pressing issues.

**Comment by aidan-fitz** [comment]
How big would the chunks be? If each one is the same size as a block, you'd have slack space between them and no space would be saved.

**Comment by imperative** [comment]
Well obviously you wouldn't have a lot of slack space between them (otherwise what's the point?). In the cases where some random-access modification would produce new chunks which would introduce slack space, such slack space would be transparently re-arranged (very slow, but would be done during idling) to produce a new block configuration. Technically there is no need for a miracle here, just for proper engineering, but it's a much bigger undertaking than "a couple of evenings"-sized task. 
Here are some links if you want to know how this could be done: http://stackoverflow.com/questions/236414/what-is-the-best-compression-algorithm-that-allows-random-reads-writes-in-a-file/3433182#3433182 (and all links from that answer). 
As previously stated, NTFS does this already.
(Besides the obstaacle of the sheer size of the task, another issue which I think will prevent this functionality ever making it into encfs is the security implications - http://blog.superuser.com/2011/03/21/compression-and-encryption/)

**Comment by bengoodwyn** [comment]
Would it be better to layer a compressing file system between the target file system and EncFS? There is more management on the end user, but taking something off the shelf like https://github.com/tex/fusecompress might allow implementation without bloating EncFS.

**Comment by hexadecagram** [comment]
I think it would be wise to pull in the bits from fusecompress, merge them with encfs, and go from there.

Both ZFS and btrfs have support for compression and deduplication built into the filesystem, which works great for most users that need a stable filesystem that supports compression. But users such as myself use encfs for encrypting our backups at the file level before we push them up to the cloud. Neither ZFS nor btrfs help at all in such circumstances. So why have 2 filesystem layers when you could have one?

I would urge the encfs devs to **strongly** consider this course of action. vgough is obviously a contributor here, so why not?

**Comment by benrubson** [comment]
> I don't see this happening

Clearly, not sure we will, closing this then for now...
