### ISSUE TITLE
in --public mounts permission denied with group and subgroup  

### ISSUE THREAD

**Issue by acorni** [vgough/encfs#21]
if you mount a --public encrypted volume
  encfs --public /data/encfs_data/ /data/data
you can protect a directory with groups.
If your user has groups
  groups user
  user: private veryprivate
as root you create a directory 
(/data/data/private)
 mkdir  private; cd private
 chmod 770 .
 chgrp private .
and a sub directory 
(/data/data/private/veryprivate)
 mkdir  veryprivate; cd veryprivate
 chmod 770 .
 chgrp veryprivate .
and as user "user" in "veryprivate" you try a
 cat > aa.txt
you get a
 -bash: aa.txt: Permission denied 
however you can write such file as root
and as "user" you can delete it.

if you do the same things e.g. in ext4
you are able to write such file.

**Comment by Scinawa** [comment]
I have almost the same problem.
I'm on xen+fedora21
(same problem on xen+debian, but on a vps wihtout debian and on my previous os everything was fine).


[root@localhost user]# namei -mo /var/www/html/dec/data/cache/                                                                          
f: /var/www/html/decw/data/cache/
 dr-xr-xr-x root   root   /
 drwxr-xr-x root   root   var
 drwxr-xr-x root   root   www
 drwxr-xr-x root   root   html
 drwxr-xr-x root   root   dec
 drwxrwxrwx apache apache data
 drwxrwxrwx apache apache cache


As you can see, apache should be able to write in data and cache directory. (I have edited for this purpose /etc/passwd in order to have a proper shell with the apache user)

bash-4.3$ whoami
bash: apache
bash-4.3$ echo "asd" > /var/www/html/dec/asd           # everything OK
bash-4.3$ echo "asd" > /var/www/html/dec/data/cache/asd
bash: /var/www/html/dec/data/cache/asd: Permission denied
bash-4.3$ mount -l | grep encfs
encfs on /var/www/html/dec type fuse.encfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)

I have already checked that I do not have selinux NOT enforced.
I'm on a xen machine:

/dev/xvdb on /home type ext4 (rw,relatime,discard,data=ordered)

**Comment by benrubson** [comment]
This issue should be solved thanks to #403.
I then close it, feel free to re-open if needed 👍
