### ISSUE TITLE
error if try to --reverse

### ISSUE THREAD

**Issue by ErAzOr2k** [vgough/encfs#259]
Hi,

I'm getting this error, if I try to mount in reverse with already existing config:
Die geladene Konfiguration ist mit --reverse nicht kompatibel

this is my config:

[http://pastebin.com/HxKvZjVi](http://pastebin.com/HxKvZjVi)

Is there anything I can do, to be able to reverse mounting?

**Comment by rfjakob** [comment]
No, you have to create the config with `--reverse` specified on the command line. In other words, if you want to reverse-mount the directory "a" to the mountpoint "b", you'd do
```
encfs --reverse $PWD/a $PWD/b
```

**Comment by Torsten85** [comment]
So one follow up question from me:

I've created my encfs6.xml 1 month ago and since then I'm using it by (automatically) coping files in the decrypted folder and uploading the from the encrypted folder. So I've quite a lot of encrypted files with my encfs6.xml. 
Now I'd like to use --reverse but I'm unable to due to the error mentioned above. 
Is there a way to generate a new encfs xml that allows me to decrypt all the files I already have and also lets me use reverse? Or do I have to start over?

Thanks in advance

**Comment by antofthy** [comment]
The reverse option is used to generate 'virtual' encrypted files from unencrypted files.
But your files are already encrypted.   Can you say what why you are trying to do this?

I see two things... 

1/ if you want your files saved unencrypted you will need to make a copy of them.

2/ have you tried running encfs --reverse on the encfs unencrypted files? 

that is your files are stored encrypted, you use encfs to crate a the unencrypted mount (virtual copy) of those files,  then apply encsf -reverse to create a reverse encrypted version.

NOTE: you may have to move the encfs6.xml file out of the way, but you can notify encfs of its location using a "ENCFS6_CONFIG" environment variable.

**Comment by benrubson** [comment]
@Torsten85 did you solve your problem ?

**Comment by benrubson** [comment]
@Torsten85 did you solve your problem ?
(_if so let's close this issue ? thx !_)

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!
