### ISSUE TITLE
Current master breaks tests

### ISSUE THREAD

**Issue by mouse07410** [vgough/encfs#488]
MacOS 10.13.3, Xcode-9.2:
```
. . . . .
Running tests...
Test project /Users/uri/src/encfs/build
    Start 1: unit
1/1 Test #1: unit .............................   Passed    0.13 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.14 sec
Scanning dependencies of target integration
++ dirname ../integration.sh
+ cd ..
+ perl -I. -MTest::Harness -e '$$Test::Harness::debug=1; runtests @ARGV;' integration/normal.t.pl integration/reverse.t.pl
integration/normal.t.pl ... 
runTests: mode=standard sudo=off
integration/normal.t.pl ... 64/136 
runTests: mode=paranoia sudo=off
integration/normal.t.pl ... ok       
integration/reverse.t.pl .. 18/36 Use of uninitialized value $dec in string eq at integration/reverse.t.pl line 131.

#   Failed test 'symlink to '/1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/15/17/18''
#   at integration/reverse.t.pl line 131.
Use of uninitialized value $dec in concatenation (.) or string at integration/reverse.t.pl line 131.
integration/reverse.t.pl .. 36/36 # Looks like you failed 1 test of 36.
integration/reverse.t.pl .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/36 subtests 

Test Summary Report
-------------------
integration/reverse.t.pl (Wstat: 256 Tests: 36 Failed: 1)
  Failed test:  24
  Non-zero exit status: 1
Files=2, Tests=172, 43 wallclock secs ( 0.07 usr  0.02 sys + 16.22 cusr  2.78 csys = 19.09 CPU)
Result: FAIL
Failed 1/2 test programs. 1/172 subtests failed.
make[3]: *** [CMakeFiles/integration] Error 1
make[2]: *** [CMakeFiles/integration.dir/all] Error 2
make[1]: *** [CMakeFiles/integration.dir/rule] Error 2
make: *** [integration] Error 2
$ 
```

**Comment by benrubson** [comment]
Thx Mouse for the report.
Every time you launch integration tests you face this issue ?
Or it is sporadic ?
Anyway, quite strange.

**Comment by mouse07410** [comment]
> Every time you launch integration tests you face this issue? Or it is sporadic ?

:-(   Sporadic. :-(

**Comment by mouse07410** [comment]
> That's embarrassing, as I can't find what in the previous commits could lead to this issue.

That makes two of us. :-(

But it looks like this failure is irregular...

> Every time it fails, this is with the same error as above ?

Yeah, both times that it failed, out of **multiple** test-runs...

**Comment by benrubson** [comment]
To sum-up last commits :
- **Revert from/to link parameters for readability** : well we just inverted some parameter names ;
- **Notify about Win port** : text only ;
- **Correct MAC typo in FS creation** : text only ;
- **Do not count usage on root path** : very simple code ;
- **Ignore .encfs6.xml file in reverse mode** : code is rather simple too ;
- **Corrects encfsctl cat and add reverse cat** : only affects encfsctl binary (and new reverse tests) ;
- **Add -c & -u cmdline options** : I see no reason why it would impact symlinks ;
- **Improve .encfs6.xml test** : only affects a new reverse test.

I've opened #490 to improve symlink tests, to have a clear view where they fail.

Would `encfsctl` tests, which run before link tests, have an impact ?
Would the new unmount method have an impact ?
Is this issue here since a long time and was "hidden" by the previous unmount issue (#428) ?

**Comment by benrubson** [comment]
I would also suspect the same thing.
However, in `reverse.t.pl`, unmount comes at the very end of the script, so after all tests are done.
So I also think we should have seen these errors, even facing the unmount issue (#428)...
Hard to be sure though.

**Comment by benrubson** [comment]
Try with last master ?
Symlink tests have been improved. Thx 👍

**Comment by mouse07410** [comment]
Trying it now...

**Comment by mouse07410** [comment]
What can I say? The darn thing passes the integration tests... Let's wait another few months till this problem resurfaces again, for reasons unknown...

**Comment by mouse07410** [comment]
Closing this issue, at least for now - as at this time all the tests pass OK.

**Comment by benrubson** [comment]
Thx Mouse 👍
