### ISSUE TITLE
successful build on mac os x label:"question"

### ISSUE THREAD

**Issue by VC-H** [vgough/encfs#532]
Thanks for making and maintaining encfs.

Recently I successfully built encfs on a Mac OS X (El Capitan) 10.11.6.

I request if my example is useful in [the wiki](https://github.com/vgough/encfs/wiki/Mac-OS-X)

- Setup:
  - binary installation of the [osxfuse](https://osxfuse.github.io/) pkg v3.8.0
  - macports 2.5.3 minimum installed with
    - cmake
    - openssl

- Build (ref: ``INSTALL.md``):
```bash
cd build
cmake .. -DENABLE_NLS=OFF -DOPENSSL_ROOT_DIR=/opt/local -DCMAKE_INSTALL_PREFIX=$HOME/example
make
```

**Comment by benrubson** [comment]
Done, thank you for your contribution @VC-H 👍 
@mouse07410, I know you also widely use MacOS, feel free then to comment !
Thx !

**Comment by mouse07410** [comment]
I concur wrt. installing `osxfuse` (when the Macports-based version works, I use it; otherwise just download it from https://osxfuse.github.io . I use OpenSSL-1.0.2 installed via Macports (currently 1.0.2o). It is not recommended to use OpenSSL that's bundled with MacOS, and highly unlikely to work.

Here's my build script `build-macports.sh`, that served me well so far:
```
#!/bin/bash -eu

: ${CMAKE:=cmake}
: ${CHECK:=false}
: ${INTEGRATION:=true}

${CMAKE} --version

CFG=$*
if [[ "$CHECK" == "true" ]]; then
  CFG="-DLINT=ON $CFG"
fi

if uname -s | grep -q Darwin; then
  CFG="-DENABLE_NLS=OFF -DOPENSSL_ROOT_DIR=/opt/local -DCMAKE_INSTALL_PREFIX=/opt/local $CFG"
fi

rm -rf build

if [[ ! -d build ]]
then
  mkdir build
fi

cd build
${CMAKE} .. ${CFG}
make -j2
make unittests
make test
if [[ "$INTEGRATION" == "true" ]]; then
  make integration
fi

cd ..

echo
echo 'Everything looks good, you can install via "make install -C build".'
```

You might want to include it in the source tree...

**Comment by benrubson** [comment]
Thank you @mouse07410 👍 
You both use `-DENABLE_NLS=OFF`, the required library is not available ?
I'm thinking about adding required flags to `CMakeLists.txt` so that it builds out of the box.
