### ISSUE TITLE
Outer password / fake content feature request

### ISSUE THREAD

**Issue by Raj2032** [vgough/encfs#533]
I wanted to suggest a feature something that is preseant in Veracrypt. In Veracrypt, the user is able to have an outer and inner passwords. The outerpassword would unlock something that would present fake files that the user can add, while the inner password can unlock the real hidden files.

This feature would be very great if it were implemented as if the user is forced to give up their encrypted passwords, they can give the fake password that will unlock something else without revealing their real hidden files.

**Comment by Keisial** [comment]
encfs does a per-file encryption. As such, I feel this is not doable. Even if you stored two copies per file (real + fake), the size difference between encrypted and decrypted would leak the use of double passwords.

(Veracrypt can do that since it encrypts the full fisk, as such the files are hidden as "unused disk space")

**Comment by benrubson** [comment]
I think there's no chance EncFS will support this, especially for above reasons.
I don't see how this could be feasable, especially if you want the content / files to seem "real" in both cases.

**Comment by Francewhoa** [comment]
At Ubertus we're also interested in this new feature

In the future, if somehow find a way to do this, the Ubertus team would be happy to contribute testing and documentation, if needed

**Comment by Joe23232** [comment]
Oh nice @Francewhoa But what is Ubertus?

**Comment by Francewhoa** [comment]
> what is Ubertus?

Thanks for asking @Joe23232 :) The Ubertus team are both enthusiasts and active contributors to open source software which are owned by not-for-profit communities. Open source software such as, but not limited to, http://AegirProject.org, https://Debian.org, https://Drupal.org, https://Eclipse.org, https://Hubzilla.org, https://LineageOS.org, https://Mozilla.org, https://OpenStack.org, https://Virtualmin.com, https://Webmin.com, and https://Wordpress.org.

Ubertus work in collaboration with government agencies and not-for-profit organizations to successfully achieve their goals. We are highly skilled in large-scale digital products. Since 1995 Ubertus offers services for all aspects of digital products. Ranging from concept to support. https://ubertus.org

**Comment by Joe23232** [comment]
> Thanks for asking @Joe23232 :)

No worries man :)

> Ubertus work in collaboration with government agencies and not-for-profit organizations to successfully achieve their goals. We are highly skilled in large-scale digital products. Since 1995 Ubertus offers services for all aspects of digital products. Ranging from concept to support. https://ubertus.org

Very interesting, I will have a look at it mate :)
