### ISSUE TITLE
Question about Encfs.

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [vgough/encfs#571]
After running `encfs ~/encrypted/ ~/decrypted/`

If I add files to` ~/decrypted/` , will the files be written to the disk in `~/decrypted/` ? if so, isn't it a security issue when someone steals your laptop and takes out the disk ?

If they are not written to the disk, where are they kept ?

Also, There is a security concern about Encfs:

> EncFS is probably safe as long as the adversary only gets one copy of the ciphertext and nothing more. EncFS is not safe if the adversary has the opportunity to see two or more snapshots of the ciphertext at different times. EncFS attempts to protect files from malicious modification, but there are serious problems with this feature.

If I use Encfs personally, without uploading anything to the cloud, Am I affected by this ?

How can someone get their hands on two copies of an encrypted file ? Is it like this:

pasting `file.txt` to `~/decrypted/` then there will be an encrypted file in `~/encrypted/` .. call it version 1.

then at a later time, (Perhaps after umount and mount also ?) you modify `file.txt` in `~/decrypted/`, call the modified and encrypted `file.txt` in `~/encrypted/` version 2 ...

If someone has access to version 1 and 2 , then this is where Encfs becomes insecure...Am I getting this right ?

**Comment by mhogomchungu** [comment]
Files on disk will be stored encrypted in the ```encrypted``` folder.

The ```decrypted``` folder "holds" a decrypted "view" of the encrypted files that are located in the ```encrypted``` folder. You can view the ```decrypted``` folder as a tunnel door that show you a view of the files that are located in the ```encrypted``` folder

When you lock the volume with "fusermount -u ~/decrypted" command, the "tunnel" get broken and ```decrypted``` folder will now be empty because nothing is stored in this folder and the folder is used just to give a decrypted view of the encrypted files that are stored in the ```encrypted folder```.

Your understanding of the "file.txt" file scenario is correct.

**Comment by benrubson** [comment]
_Closing this, as questions seem to have been answered. Thx 👍_
