### ISSUE TITLE
Problem opening files on OS X

### ISSUE THREAD

**Issue by jooray** [vgough/encfs#70]
This is a rare issue, rare enough to be difficult to reproduce, but not rare enough to not be annoying. We use version 1.8 installed from homebrew. 

How to reproduce (when this happens):
1. Double-click on the file (in this case PDF, but same happens with Word for example)
2. Dialog window saying "File_1" is damaged and can't be opened. You should eject the disk. It also says "Preview created this file on {date}.", which is correct. There are two options: Cancel and Eject Disk

If I copy this file to /tmp, I can open it, they are even same:

```
$ md5 encfs/File_1.pdf
MD5 (encfs/File_1.pdf) = 0bc06a6fae03f2ca9c4c55cd7cd81ad4
$ md5 /tmp/File_1.pdf
MD5 (/tmp/File_1.pdf) = 0bc06a6fae03f2ca9c4c55cd7cd81ad4
```

The underlying folder is synchronized using Synology CloudStation (private Dropbox alternative), so this may be related. It does not happen with unencrypted folder, so it's either an encfs issue or encfs+Synology CloudStation interaction issue. Internally, it's like dropbox, synchronizes the underlying files when they change (so it's not using FUSE or mount any other filesystem, it's an userspace application). Also noted: This file has been synchronized months ago and has not been changed, so it's probably not a locking issue and for sure not a synchronization conflict issue.

**Comment by robbwagoner** [comment]
I have had the same problem with encfs 1.7.4 on Dropbox too. PDFs and MS Office documents experience the same problem. If I copy the file to a non-encfs location, it opens without issue.

**Comment by jooray** [comment]
Thanks, so it's probably not a Synology issue per-se. It may be related to the files changing outside of encfs layer.

Has anyone reproduced this on pure encfs (without Dropbox or any other file synchronisation tool?)

**Comment by jooray** [comment]
I think the issue is described here:

https://forums.boxcryptor.com/topic/boxcryptor-on-os-x-does-not-decrypt-files

(BoxCryptor uses encfs as a backend).

They also issued this official statement:

https://boxcryptor.desk.com/customer/portal/articles/688364-why-am-i-receiving-the-error-filexyz-is-damaged-and-can-t-be-opened-you-should-move-it-to-the-trash-%22-under-mountain-lion-

The question is how to handle this issue in a systematic way.

Anyway, I cannot reproduce this right now.

**Comment by rfjakob** [comment]
Yes, this is the `com.apple.quarantine` xattr issue. If have seen this a lot on NFS drives, this is not an encfs issue. However, if there are ideas to work around that pathological behavoir of Mac OS, I'm open for ideas.

**Comment by jooray** [comment]
The question is if it's an issue of the attribute on encfs. Having an option to remove this xattr attribute even if it's set on underlying file might solve this issue, if I am not mistaken.

**Comment by rfjakob** [comment]
Could you check if `com.apple.quarantine` is even set on the underlying encrypted file? You can get the filename using

    encfsctl encode /encfs/underlying/directory path/to/broken/file

**Comment by jooray** [comment]
Right now I can't even reproduce it again, so I'll have to wait until this occurs again.

**Comment by jooray** [comment]
OK, I was able to reproduce it. It is set on the underlying file. I did ```encfsctl encode``` as rfjakob suggested, found the underlying file and deleted the attribute. The file opened.

Right now the best workaround I know about is doing this before mounting:

    xattr -d -r com.apple.quarantine /encfs/underlying/directory

Option to not transfer this flag would be still helpful, since the file shows as damaged (instead of being downloaded from the internet as would be the case with original file).

**Comment by jooray** [comment]
Sorry, it works only if I do it after mounting for some weird reason.

**Comment by Thinkscape** [comment]
Same here. Cannot open files even though they're stored correctly.

The temp and annoying workaround involves clearing the attribute, but on MOUNTED volume, not the storage volume:

    xattr -r -d com.apple.quarantine /Volumes/myEncryptedVolume

**Comment by Thinkscape** [comment]
Related upstream bug report https://github.com/osxfuse/osxfuse/issues/162

**Comment by mehaase** [comment]
I get this issue reliably: OS X 10.10, oxsfuse (compiled from master branch today), and encfs (compiled from master branch today). I was getting the same issue on OS X 10.9, too, and the issue occurs with the homebrew packages for osxfuse and encfs.

This happens from a brand new volume created in my home directory. I notice the problem with many different apps, mainly testing with Pages but also occurring with Preview and Numbers, etc.

    $ encfs -f ~/temp1 ~/temp2 -o volname="Temp2"
    # go through the new volume wizard

Then: 

* Create new Pages document, save it in temp2, and close it.
* Find new document in Finder and double click to open.
* Get error: "TESTING.pages is damaged and can’t be opened. You should eject the disk. Pages created this file today at 7:22 PM"
* Clicking "Eject Disk" results in an error.

![screen shot 2015-06-22 at 7 24 04 pm](https://cloud.githubusercontent.com/assets/320904/8295595/477c373c-1914-11e5-85ff-d83a54dd80c1.png)

The issue can be temporarily fixed by deleting the quarantine attribute, either on the plaintext file or the ciphertext file. The attribute is re-applied whenever the file is opened and then saved.

Oddly, although the file cannot be opened from Finder, it can be opened without error by going into Pages and choosing `File → Open. Apparently the quarantine flag is enforced only by Finder and Pages is unaware of it.

**Comment by rfjakob** [comment]
Maybe we could do something like this: https://github.com/osxfuse/osxfuse/issues/162#issuecomment-114235909

**Comment by vgough** [comment]
Is there a repro case which doesn't involve commercial software (Pages), please add it here, or else check if #107 improves on your case.

**Comment by poiru** [comment]
The latest release of FUSE for OS X fixes this issue. See [kext commit](https://github.com/osxfuse/kext/commit/3c5069775c4a0aef52784a898b1519b2710d03a4).

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake, then let me know and I'll re-evaluate.
