### ISSUE TITLE
Option to split large files (set max file size)

### ISSUE THREAD

**Issue by tmanka** [vgough/encfs#76]
Would be great to have a flag to split large files into smaller encrypted files.  This would allow for people to take advantage of the unlimited cloud storage offerings which have max file size limits (amazon cough cough)

**Comment by Aikhjarto** [comment]
I use a backup software which does split large files in junks. Then I encrypt the backup and have no problems with too large files. This also saves bandwidth when uploading a changed file.

**Comment by tmanka** [comment]
What software do you use?  I will check it out.  Would still be great if this were a native option in encfs....I don't *think* this would be too high of a hurdle and would have some pretty positive effects and IMO lead to higher adoption of ENCFS.

**Comment by rfjakob** [comment]
Are you talking about amazon s3? What is the maximum file size?

**Comment by Aikhjarto** [comment]
@tmanka i personally use storeBackup but other backup tools that do blockwise backup should be usable. Like attic, zbackup, bup

**Comment by tmanka** [comment]
@rfjakob Talking about the new unlimited amazon cloud storage for $60 for the year.  I have some files above the 2gig limit which I would like to get up there but also have encrypted as I TNO (trust no one)  @Aikhjarto I will check out what you listed and see if one of those options can chain with encfs to accomplish the goal.

**Comment by rfjakob** [comment]
This feature would add a lot of complexity and additional code paths, all with possible bugs that cause data loss. To be honest, I think this should not be implelemted. Vagrant, what do you think?

**Comment by vgough** [comment]
@rfjakob were you asking me?  I think it's an interesting feature, but it since it would change the 1:1 file mapping which has always been an assumption until now, it would indeed be a major change.

**Comment by Manouchehri** [comment]
@tmanka A solution would be to use losetup. I think that's the route I'm going to go for Microsoft OneDrive, as there's a maximum limit of 20,000 files at 10GB each (giving 200 TB if each file is the maximum size).

Although, if I'm going with losetup, I'm not sure if there's much difference between using EncFS and plain old LUKS in the end.

**Comment by Aikhjarto** [comment]
> @Aikhjarto I will check out what you listed and see if one of those options can chain with encfs to accomplish the goal.

@tmanka Actually, I use storeBackup in combination with encfs and then rsync to copy the backup. The rsync part may be subject to be replaced by skicka in the future.

**Comment by tmanka** [comment]
Hi @Manouchehri and @Aikhjarto This losetup sounds interesting.  Can you mount a losetup + encfs (folder?) as a drive and have it be transparent to the OS?  This is sounding interesting.  I googled around a bit on losetup but I am not seeing how I would use it in this context.  Would you please walk me through your setup?  Much appreciated!

**Comment by Aikhjarto** [comment]
With losetup you can generate an encrypted container file. The container is a binary file which most likely will result in large overhead when syncing to an off-site location, i.e. algorithm like rsync will transfer the whole even when only 1 byte has been changed.
Here enfcs is much better, since rsync-like algorithm will only transfer the changed files.

**Comment by brianvanderburg2** [comment]
I was also looking for a feature like this.  It could provide some security advantages as well.  As it is, given a large enough file set it may be possible to determine what the files are based on the number of files in the directories and the approximate sizes of the files.  If large files could be broken into smaller parts, this could make that harder, though it could still be possible to determine the approximate total size of each directory and perhaps determine content based on the number of directories and sub directories and the approximate total sizes.

However, since it would break the one-to-one mapping, each directory would then need some sort of index.  If such a route is chosen to break files into smaller parts, I wouldn't see any reason to keep a one-to-many mapping any longer.  Instead, an object store, perhaps something similar to git's object structure, could exist which would store the encrypted objects in pieces of limited sizes, where each object could be part of a file or part of a directory index.  Even with a system like this, changing a single file in the plaintext would only change a limited set of files in the ciphertext, so syncing the results to a remote location would not require a complete transfer of all files, only those changed files.

**Comment by Manouchehri** [comment]
For me, the biggest benefit of EncFS is the one-to-one mapping. Without that, there's not much reason that I can see to *not* use LUKS.

@Aikhjarto: zsync would probably help a lot. If you change 10MB in a 10GB container, hopefully only ~10MB will have to be transferred over. I haven't benchmarked it though.

Ubuntu uses zsync to keep their ISOs up to date; you could probably do something similar with an encrypted container. http://cdimage.ubuntu.com/daily-live/20150422/

**Comment by benrubson** [comment]
> To be honest, I think this should not be implelemted.

I think so too, let's then close this for now...
