### ISSUE TITLE
Accept donations

### ISSUE THREAD

**Issue by fulldecent** [vgough/encfs#77]
Encfs is an important project for many of us and users would like to see consistent releases and thoughtful attention paid to the project by internal and external contributors.

For users that can't fix bugs and make test cases, I recommend that donations be a way that those users can give back to the project.

Please set up an account to receive donations and advertise this on the README.md, the `--help` screen, and/or the project homepage.

**Comment by msx** [comment]
I second this request.
However in my case at the time I can donate only via Bitcoins; I would be glad to do so.

**Comment by akerl** [comment]
This is why accepting donations ends up being a ton of complexity (read: work): everybody wants donations to be advertised/handled/used in the way they think best, and wants them accepted via their preferred stream.

Since it's been brought up, I cannot imagine having a command line tool request donations via CLI --help output. Are there actually tools that do this?

**Comment by fulldecent** [comment]
Whatever @vgough does we will all be cool with.

**Comment by msx** [comment]
Well, in my case the mafia that rules the administration on the country I live in applies an extra 35% fee over all foreign purchases in concept of 'advanced income tax' - fancy words for saying 'we steal and spend more money than we got and we need more, f*ck y'all'.
I would love to donate via CC but under these terms I won't, that's why I'm asking the team behind EncFS if they accept bitcoins.

**Comment by vgough** [comment]
@rfjakob has been the driving force behind the recent release, so he's welcome to take donations if he wants.  Although I'd limit advertisement to the github pages for now.  Sponsoring issues via bounties is another idea.

**Comment by rfjakob** [comment]
I think bounties are a better way to contribute financially. They attract new developers.

**Comment by fulldecent** [comment]
Added a bounty on https://github.com/vgough/encfs/issues/55 which effectively resolves this issue.
