### ISSUE TITLE
getsafe uses encfs but has no xml-config

### ISSUE THREAD

**Issue by Aikhjarto** [vgough/encfs#98]
I stumbled over a very interesting project that uses encfs as base:
http://www.getsafe.org/about
https://github.com/safeapp/safe

One goal is to provide enfcs to windows users. Unfortunately, their fork of encfs does not write and xml as config file but some other structure. Here is an example:
```
creator: "EncFS 2.0"
revision: 20120902
cipher {
  name: "ssl/aes"
  major: 3
  minor: 1
  age: 2
}
key {
  ciphertext: "\231\206\376`\246\265\374\273TU\226\232;}\214\357=\276\006\276\r\271\275\277\271^\222Q\341\240\352X<B\342\"\240M\036\320s9\374e\354l\271{\027d\325\370"
  size: 32
  salt: "\314\227T\225\361\214\0048\177\317\001\265\260\341Av%\303\337E"
  kdf_iterations: 426666
  kdf_duration: 3000
}
naming {
  name: "nameio/block32"
  major: 4
  minor: 0
  age: 2
}
block_size: 2048
writer: "EncFS 2.0"
unique_iv: true
chained_iv: true
external_iv: true
block_mac_bytes: 8
allow_holes: true
block_mac_rand_bytes: 0
```

Now I'm a bit confused. 
Firstly, they claim to use encfs 2.0, but encfs is at 1.8.1. Is that really a fork of this encfs project, or something different?
Secondly, I wonder if it's possible to parse the above mention config file with encfs 1.8.1?

**Comment by vgough** [comment]
Based on this file, I suspect that they branched from a development version, which reported itself as encfs 2.0 (but was never released as such).  This file looks like the text encoding of a Protocol Buffer config, which is what I was using on development.  That code was never fully stabilized, so I've started picking out changes for inclusion into the stable branch rather than taking the entire thing as the next version of encfs.

You can find the protocol buffer description on the dev branch: https://github.com/vgough/encfs/tree/dev/protos

The code to decode it is in the dev branch as well.
